[tool.poetry]
name = "music-python"
version = "0.1.0"
description = ""
authors = ["cainky <kylecain0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mido = "^1.2.10"
music21 = "^8.1.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.1"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
