[tool.poetry]
name = "midigen"
version = "0.1.0"
description = ""
authors = ["cainky <kylecain0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
mido = "^1.2.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
